version: '3.4'

services:
  naming-server:
    image: guiscarabelli/naming-server:0.0.1-SNAPSHOT
    ports:
      - 8761:8761
    networks:
      - my-network
  zipkin:
    image: openzipkin/zipkin
    ports:
      - 9411:9411
    networks:
      - my-network
networks:
  my-network:
    driver: bridge