spring:
  application:
    name: book-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/book_service
    username: root
    password: gUiGuI#08410
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  flyway:
    url: jdbc:mysql://localhost:3306/
    schemas: book_service
    user: root
    password: gUiGuI#08410
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
management:
  endpoints:
    web:
      exposure:
        include: '*'
server:
  port: 8100
resilience4j:
  bulkhead:
    instances:
      default:
        max-concurrent-calls: 10
  ratelimiter:
    instances:
      default:
        limit-for-period: 2
        limit-refresh-period: 10s
  retry:
    instances:
      foo-bar:
        max-attempts: 5
        wait-duration: 1s
        enable-exponential-backoff: true