name: Continuous Integration with Github

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Setup Java JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Build Eureka Naming Server Container Image
        working-directory: ./connecting-microservices/naming-server
        run: |
          mvn spring-boot:build-image -DskipTests
          docker tag naming-server:0.0.1-SNAPSHOT ${{ secrets.DOCKERHUB_USERNAME }}/naming-server:0.0.1-SNAPSHOT

      - name: Build API Gateway Container Image
        working-directory: ./connecting-microservices/api-gateway
        run: |
          mvn spring-boot:build-image -DskipTests
          docker tag api-gateway:0.0.1-SNAPSHOT ${{ secrets.DOCKERHUB_USERNAME }}/api-gateway:0.0.1-SNAPSHOT

      - name: Build Cambio Microservice Jar
        working-directory: ./connecting-microservices/cambio-service
        run: |
          mvn clean package -DskipTests
          docker build -t cambio-service:latest .
          docker tag cambio-service:latest ${{ secrets.DOCKERHUB_USERNAME }}/cambio-service:latest

      - name: Build Book Microservice Jar
        working-directory: ./connecting-microservices/book-service
        run: |
          mvn clean package -DskipTests
          docker build -t book-service:latest .
          docker tag book-service:latest ${{ secrets.DOCKERHUB_USERNAME }}/book-service:latest
        
      - name: Docker Compose Build
        working-directory: ./connecting-microservices
        run: docker-compose build

      - name: Verify Images
        run: |
          docker images
          docker image inspect ${{ secrets.DOCKERHUB_USERNAME }}/naming-server:0.0.1-SNAPSHOT || exit 1
          docker image inspect ${{ secrets.DOCKERHUB_USERNAME }}/api-gateway:0.0.1-SNAPSHOT || exit 1
          docker image inspect ${{ secrets.DOCKERHUB_USERNAME }}/cambio-service:latest || exit 1
          docker image inspect ${{ secrets.DOCKERHUB_USERNAME }}/book-service:latest || exit 1

      - name: Tag and Push Docker Images
        run: |
          docker tag ${{ secrets.DOCKERHUB_USERNAME }}/naming-server:0.0.1-SNAPSHOT ${{ secrets.DOCKERHUB_USERNAME }}/naming-server:${{github.run_id}}
          docker tag ${{ secrets.DOCKERHUB_USERNAME }}/api-gateway:0.0.1-SNAPSHOT ${{ secrets.DOCKERHUB_USERNAME }}/api-gateway:${{github.run_id}}
          docker tag ${{ secrets.DOCKERHUB_USERNAME }}/cambio-service:latest ${{ secrets.DOCKERHUB_USERNAME }}/cambio-service:${{github.run_id}}
          docker tag ${{ secrets.DOCKERHUB_USERNAME }}/book-service:latest ${{ secrets.DOCKERHUB_USERNAME }}/book-service:${{github.run_id}}

          docker push ${{ secrets.DOCKERHUB_USERNAME }}/naming-server:${{github.run_id}}
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/api-gateway:${{github.run_id}}
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/cambio-service:${{github.run_id}}
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/book-service:${{github.run_id}}
