name: Docker Hub Login

on: [push]

jobs:
  login:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Setup Java JDK
      uses: actions/setup-java@v4.2.1
      with:
        java-version: '17'
        distribution: 'adopt'

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Start Docker daemon
      run: sudo service docker start

    - name: Build Eureka Naming Server Container Image
      working-directory: ./connecting-microservices/naming-server
      run: mvn clean package docker:build -t guiscarabelli/naming-server:latest -Dpush=true
